version: '3.8'
services:
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elastic
    restart: always
    environment:
      - node.name=elastic
      - network.host=0.0.0.0
      - cluster.initial_master_nodes=elastic
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ports: 
      - 9200:9200
    networks:
      - elastic
  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    restart: always
    volumes:
      - "./kibana.yml:/usr/share/kibana/config/kibana.yml"
    ports:
      - 5601:5601
    networks:
      - elastic
networks:
  elastic:
    driver: bridge

